"""add webhook url column for user

Revision ID: 1275dea18102
Revises: cc6084ce7f49
Create Date: 2025-12-03 11:20:50.572982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1275dea18102'
down_revision = 'cc6084ce7f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###
