"""Add api_token column to users

Revision ID: 54783273a4e9
Revises: dcffeb89e9cf
Create Date: 2025-10-16 00:42:34.661864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54783273a4e9'
down_revision = 'dcffeb89e9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_users_api_token', ['api_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
